### ISSUE TITLE
Opt out

### ISSUE THREAD

**Issue by samtingleff** [digi-trust/dt-cdn#1]
spec tbd

Need a javascript API for third parties to communicate an opt out into the system.

Requirements
- implementing partners are required to communicate an "opt out" to DT, such that an opt out from any one member becomes an opt out for the DT identity
- it must be impossible for an attacker to place an image tag or piece of javascript on a high volume web site which would opt out all viewers of the page

**Comment by mmukhin** [comment]
@samtingleff 
A straight forward solution would be a redirect to a styled "Opt-in Status" page on DT domain. 
When a parameter is passed ?optOut=1, put a nice big red button that says "Opt Out".
The user only opts out after 2 clicks (one on the client page, one on our page).
Optional: We have an opportunity to explain what DigiTrust is and how it betters their online experience.

e.g. client
DigiTrust.redirectOptOut();

**Comment by mmukhin** [comment]
> When a parameter is passed ?optOut=1, put a nice big red button that says "Opt Out".
Don't even need to pass the parameter. Just always have a "Status" and a red "Opt Out" button.

**Comment by mmukhin** [comment]
Done
