### ISSUE TITLE
Move to Akamai CDN

### ISSUE THREAD

**Issue by mmukhin** [digi-trust/dt-cdn#11]
Current headers:

Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Cache-Control: no-transform, public, max-age=3600, s-maxage=3600
Content-Security-Policy: default-src https://cdn.digitru.st; script-src 'self' 'unsafe-inline'; child-src 'none'; object-src 'none'
Content-Type: text/html
ETag: "57891754-1a0a"
Last-Modified: Fri, 15 Jul 2016 17:03:16 GMT
p3p: CP="NOI CURa ADMa DEVa TAIa OUR BUS IND UNI COM NAV INT"
Server: nginx
Vary: Accept-Encoding
Content-Encoding: gzip
Date: Mon, 18 Jul 2016 01:34:31 GMT
Content-Length: 1208
Connection: keep-alive

**Comment by samtingleff** [comment]
released
