### ISSUE TITLE
Minify JS and HTML

### ISSUE THREAD

**Issue by muuki88** [digi-trust/dt-cdn#35]
Hi,

Google Page Speed recommends to minify java script assets. It seems that neither the digitrust server nor client are minified. This is crucial for an optimal user experience, fast ad loading and high SEO visibility.

The report states that
```
Minifying https://cdn.digitru.st/prod/1.4.0/digitrust-server.js could save 3.7KiB (16% reduction) after compression.
Minifying https://cdn.digitru.st/prod/1.4.0/digitrust.js could save 3.7KiB (16% reduction) after compression.
```

If you accept pull requests for this addition let me know.

cheers,
Muki

**Comment by samtingleff** [comment]
Hi @muuki88 thanks for pointing this out. Our docs have updated to point to digitrust.min.js, and we're already minifying digitrust-server.js, so I think the most important change would be to make use of digitrust-server.min.js from within pages/dt.html.

**Comment by samtingleff** [comment]
I've pushed this change into master and will release with 1.4.3.

PRs are of course welcome! :)

**Comment by samtingleff** [comment]
Resolved in 1.4.3 and /1/ major release.

**Comment by muuki88** [comment]
Thanks a lot for fixing this. We will contact our advertisers to update to the latest version.

**Comment by muuki88** [comment]
You mention the release, but there are no git tags for the release.
It would be nice to see the different releases along with a changelog :)
