### ISSUE TITLE
Cookie delete from trusted clients

### ISSUE THREAD

**Issue by samtingleff** [digi-trust/dt-cdn#5]
We would like for the [demo page](http://www.digitru.st/client-demo/) to allow for a full cookie delete when the reset button is pressed. However in general we do not want arbitrary web sites to have the ability to execute a bit of javascript which results in the deletion of DigiTrust cookies. So, how can we allow for this, yet ensure that only code executing on .digitru.st has the ability to do so?

Here's one idea
- within the code executed by reset, set a .digitru.st cookie of the form "DeleteEverything=true"
- send a message to the dt.html iframe of the form "hey, delete all the cookies"
- within dt.html, delete all cookies

**Comment by mmukhin** [comment]
Pushed to "develop" and deployed "develop" to production.

**Comment by mmukhin** [comment]
1) Test on prod, http://www.digitru.st/client-demo/
2) Accept https://github.com/digi-trust/dt-cdn/pull/7
3) Close this
