### ISSUE TITLE
Build DigiTrust pre-bid module

### ISSUE THREAD

**Issue by anissaconnor** [digi-trust/dt-cdn#56]
[DigiTrust Module for Pre-bid.js PRD](https://docs.google.com/document/d/1Jkn6Gr3S1JDbqagXROu4CymsfsV_g86ieng3m7YaaGc/edit#heading=h.b0wei4bwogsr)

**Objective:**

To make a DigiTrust integration easier for publishers that are implementing pre-bid.js. Create a DigiTrust module that is approved by pre-bid that allows publishers to download the DigiTrust JS as part of their pre-bid package. DigiTrust should just be another tick box underneath the ‘Modules’ section of the Pre-bid package build (see attached image).

**User Stories:**

- As a publisher, I would like to implement the DigiTrust JS as part of my pre-bid package so I do not have to implement it on my page as a standalone piece of JS.
- As a publisher, I would like to understand what the DigiTrust module does so I can decide whether to add it to my pre-bid build. (Documentation)

- As a publisher, I would like to understand how I become a DigiTrust member and the tasks I need to undertake to successfully implement the DigiTrust module as part of my pre-bid package. (Documentation - steps outlined at www.digitru.st/publishers)
- As a publisher, I would like to understand the configuration options available in the DigiTrust module so I can decide on the best configuration of DigiTrust in my pre-bid package. (Documentation)

**High Level Task Summary**

- Review Prebid Modules (http://prebid.org/dev-docs/modules/)
- Review DigiTrust Prebid Module (http://prebid.org/dev-docs/modules/digitrust.html)
- Bring DigiTrust Prebid Module in-line with general Prebid Module architecture of current Prebid version (https://github.com/prebid/Prebid.js/tree/master/modules) adhering to pre-bid code of conduct and principles.
- Test and verify Module works as expected
- Create necessary DigiTrust Module page (documentation). Documentation should cover:
- Benefits of a DigiTrust deployment
- Steps required to become a DT member and implement DT as a publisher (outlined at www.digitru.st/publishers)
- Configuration options within the DT JS and what they do
- Manage Pull Request (PR) into Prebid
- Write up management process for future deployments (documentation for updates to DigiTrust Module)
- Update DigiTrust Github with links to DigiTrust pre-bid module page

**Comment by goosemanjack** [comment]
Preliminary code written. Submission pending review and integration of the Universal Id enhancement to Prebid.

**Comment by goosemanjack** [comment]
This code has be released and integrated into Prebid.
